[package]
name = "solana-devtools-macros"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
solana-sdk = { workspace = true }

[dev-dependencies]
itertools = "0.12.0"